# Generated by Django 6.0.6 on 2026-07-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainnote',
            name='source_type',
            field=models.CharField(choices=[('aula', 'Aula'), ('framework', 'Framework'), ('summary', 'Summary'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
