# Generated by Django 6.0.4 on 2026-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instrutor', models.CharField(max_length=100)),
                ('progresso', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
    ]
