# Generated by Django 6.0.4 on 2026-04-09 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('special', 'Especial')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('xp', models.IntegerField(default=0)),
                ('meta', models.IntegerField(default=1)),
                ('icon', models.CharField(default='target', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('total_aulas', models.IntegerField(default=0)),
                ('duracao_total', models.CharField(blank=True, max_length=50)),
                ('xp_total', models.IntegerField(default=0)),
                ('nivel', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], default='Iniciante', max_length=20)),
                ('tem_certificado', models.BooleanField(default=True)),
                ('num_secoes', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('thumbnail', models.URLField(blank=True)),
                ('area', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('objetivo', models.CharField(choices=[('Carreira', 'Carreira'), ('Habilidade', 'Habilidade')], default='Habilidade', max_length=20)),
                ('duracao_total', models.CharField(blank=True, max_length=50)),
                ('xp_total', models.IntegerField(default=0)),
                ('tem_certificado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso (legado)', 'verbose_name_plural': 'Cursos (legado)'},
        ),
        migrations.CreateModel(
            name='TrilhaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('prerequisito', models.CharField(blank=True, max_length=200)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.trilha')),
            ],
            options={
                'verbose_name': 'Módulo da Trilha',
                'verbose_name_plural': 'Módulos das Trilhas',
                'ordering': ['ordem'],
                'unique_together': {('trilha', 'modulo')},
            },
        ),
        migrations.AddField(
            model_name='trilha',
            name='modulos',
            field=models.ManyToManyField(blank=True, through='cursos.TrilhaModulo', to='cursos.modulo'),
        ),
        migrations.CreateModel(
            name='ProgressoDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.IntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='cursos.desafio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_desafio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Desafio',
                'verbose_name_plural': 'Progressos de Desafios',
                'unique_together': {('usuario', 'desafio')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='cursos.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_modulo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Módulo',
                'verbose_name_plural': 'Progressos de Módulo',
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
