# Generated by Django 6.0.6 on 2026-07-03 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_desafio_modulo_trilha_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('youtube_video_id', models.CharField(max_length=50)),
                ('duracao', models.CharField(blank=True, help_text='Ex: 15:30', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursos.modulo')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['ordem'],
                'unique_together': {('modulo', 'ordem')},
            },
        ),
    ]
