# Generated by Django 6.0.6 on 2026-07-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='youtube_video_id',
            field=models.CharField(help_text='Cole a URL completa do YouTube ou apenas o ID do vídeo', max_length=50),
        ),
    ]
