# Generated by Django 6.0.6 on 2026-07-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
