# Generated by Django 6.0.6 on 2026-07-08 03:14

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Modulo = apps.get_model('cursos', 'Modulo')
    for modulo in Modulo.objects.filter(slug=''):
        modulo.slug = slugify(modulo.titulo)
        modulo.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_add_slug_to_modulo'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
