# Generated by Django 6.0.6 on 2026-07-08 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_populate_modulo_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.modulo')),
                ('trilha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.trilha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-emitido_em'],
            },
        ),
    ]
