# Generated by Django 6.0.6 on 2026-07-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recommended', 'Recomendado'), ('collab', 'Collab'), ('case', 'Case')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.URLField(blank=True)),
                ('duracao', models.CharField(blank=True, help_text='Ex: 2h 15min', max_length=50)),
                ('xp', models.IntegerField(default=0)),
                ('participantes', models.IntegerField(default=0)),
                ('badge', models.CharField(blank=True, help_text='Ex: Exclusivo, Novo', max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conteúdo em Destaque',
                'verbose_name_plural': 'Conteúdos em Destaque',
                'ordering': ['tipo', 'ordem'],
            },
        ),
    ]
