# Generated by Django 6.0.6 on 2026-07-08 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_featuredcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('verdadeiro_falso', 'Verdadeiro ou Falso')], default='multipla_escolha', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='cursos.questao')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('xp_total', models.IntegerField(default=50, help_text='XP concedido ao passar')),
                ('aprovacao_percentual', models.IntegerField(default=70, help_text='% mínima para aprovação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cursos.modulo')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['modulo', 'ordem'],
                'unique_together': {('modulo', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='cursos.quiz'),
        ),
        migrations.CreateModel(
            name='TentativaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(default=0)),
                ('total_questoes', models.IntegerField(default=0)),
                ('aprovado', models.BooleanField(default=False)),
                ('concluido_em', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='cursos.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quiz',
                'ordering': ['-concluido_em'],
            },
        ),
    ]
