# Generated by Django 6.0.6 on 2026-07-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_quiz_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativaquiz',
            name='respostas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
