# Generated by Django 6.0.6 on 2026-07-09 19:21

import cursos.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_quiz_respostas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('template', models.TextField(blank=True, help_text='HTML opcional com placeholders: {{ nome_aluno }}, {{ curso }}, {{ data }}, {{ codigo }}.')),
                ('carga_horaria', models.PositiveIntegerField(default=0)),
                ('assinatura', models.CharField(blank=True, max_length=200)),
                ('logo', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Certificado',
                'verbose_name_plural': 'Templates de Certificado',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AddField(
            model_name='aula',
            name='material_complementar',
            field=models.FileField(blank=True, upload_to='aulas/materiais/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'zip']), cursos.models.validate_upload_size]),
        ),
        migrations.AddField(
            model_name='aula',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aula',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='aula',
            name='tempo_estimado',
            field=models.PositiveIntegerField(default=0, help_text='Tempo estimado em minutos'),
        ),
        migrations.AddField(
            model_name='aula',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='video_tipo',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Upload proprio')], default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='aula',
            name='video_upload',
            field=models.FileField(blank=True, upload_to='aulas/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v']), cursos.models.validate_upload_size]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='assinatura',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='curso',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='nome_aluno',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_payload',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='modulo',
            name='ordem',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='modulo',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cursos.aula'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='feedback_automatico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_tentativas',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='url_video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Cole a URL do YouTube ou Vimeo aqui'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='cursos.certificatetemplate'),
        ),
    ]
