# Generated by Django 6.0.6 on 2026-07-08 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
