# Generated by Django 6.0.6 on 2026-07-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_bio_perfil_data_criacao_perfil_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
