# Generated by Django 6.0.6 on 2026-07-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_achievement_skill_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
