# Generated by Django 6.0.6 on 2026-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_achievement_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultimo_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
