# Generated by Django 6.0.6 on 2026-07-09 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfil_ultimo_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(default='badge-check', max_length=50)),
                ('cor', models.CharField(default='emerald', max_length=40)),
                ('xp_bonus', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('custo_moedas', models.PositiveIntegerField(default=0)),
                ('icone', models.CharField(default='gift', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['custo_moedas', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('nivel_minimo', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
                'ordering': ['nivel_minimo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='banner',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='moedas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_moedas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacao de Moedas',
                'verbose_name_plural': 'Transacoes de Moedas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('special', 'Especial')], default='daily', max_length=20)),
                ('meta', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('moedas', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.badge')),
            ],
            options={
                'verbose_name': 'Missao',
                'verbose_name_plural': 'Missoes',
                'ordering': ['tipo', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='titulo_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_ativos', to='usuarios.title'),
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.reward')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recompensa do Usuario',
                'verbose_name_plural': 'Recompensas dos Usuarios',
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(default='manual', max_length=60)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('nivel_anterior', models.PositiveIntegerField(default=1)),
                ('nivel_atual', models.PositiveIntegerField(default=1)),
                ('xp_anterior', models.PositiveIntegerField(default=0)),
                ('xp_atual', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de XP',
                'verbose_name_plural': 'Eventos de XP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.badge')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge do Usuario',
                'verbose_name_plural': 'Badges dos Usuarios',
                'unique_together': {('usuario', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.PositiveIntegerField(default=0)),
                ('concluida', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.mission')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missao do Usuario',
                'verbose_name_plural': 'Missoes dos Usuarios',
                'unique_together': {('usuario', 'mission')},
            },
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.title')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Titulo do Usuario',
                'verbose_name_plural': 'Titulos dos Usuarios',
                'unique_together': {('usuario', 'titulo')},
            },
        ),
    ]
