# Generated by Django 6.0.6 on 2026-06-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('members', models.IntegerField(default=0)),
                ('posts_today', models.IntegerField(default=0)),
                ('online_now', models.IntegerField(default=0)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('description_long', models.TextField(blank=True)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('moderators', models.JSONField(blank=True, default=list)),
                ('created_at', models.CharField(max_length=50)),
                ('related', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=300)),
                ('author_handle', models.CharField(db_index=True, max_length=100)),
                ('body', models.TextField(blank=True)),
                ('preview', models.TextField(blank=True)),
                ('post_type', models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('media', 'Media')], default='text', max_length=20)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('time_ago', models.CharField(max_length=50)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='guild.community')),
            ],
            options={
                'unique_together': {('community', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_handle', models.CharField(db_index=True, max_length=100)),
                ('body', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('time_ago', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='guild.comment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='guild.thread')),
            ],
        ),
    ]
