# Generated by Django 6.0.6 on 2026-07-09 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_comment_created_at_thread_created_at_thread_url_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='main_color',
            field=models.CharField(default='#16a34a', max_length=24),
        ),
        migrations.AddField(
            model_name='community',
            name='missions_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='community',
            name='xp_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Membro'), ('moderator', 'Moderador'), ('admin', 'Administrador')], default='member', max_length=20)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='guild.community')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guild_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integrante da Guilda',
                'verbose_name_plural': 'Integrantes das Guildas',
                'ordering': ['-xp', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('meta', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='guild.community')),
            ],
            options={
                'verbose_name': 'Missao da Guilda',
                'verbose_name_plural': 'Missoes das Guildas',
                'ordering': ['community', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='GuildMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.PositiveIntegerField(default=0)),
                ('concluida', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to='guild.guildmembership')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='guild.guildmission')),
            ],
            options={
                'verbose_name': 'Progresso de Missao da Guilda',
                'verbose_name_plural': 'Progressos de Missoes da Guilda',
                'unique_together': {('membership', 'mission')},
            },
        ),
    ]
