# Generated by Django 6.0.6 on 2026-07-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Recurso',
                'verbose_name_plural': 'Categorias de Recursos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('url', models.URLField()),
                ('autor', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(blank=True, help_text='URL pública de imagem (Unsplash, etc.)')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('Planilha', 'Planilha'), ('Prompt', 'Prompt'), ('Template', 'Template'), ('Vídeo', 'Vídeo'), ('Tool', 'Ferramenta')], default='PDF', max_length=20)),
                ('novo', models.BooleanField(default=False)),
                ('em_alta', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
